name:        persistent-qq
version:     2.9.1
synopsis:    Provides a quasi-quoter for raw SQL for persistent
description: Please see README and API docs at <http://www.stackage.org/package/persistent>.
category:    Database, Yesod
author:      Michael Snoyman <michael@snoyman.com>
maintainer:  Michael Snoyman <michael@snoyman.com>
license:     MIT
github:      yesodweb/persistent

extra-source-files:
- ChangeLog.md
- README.md

dependencies:
- base >= 4.9 && < 5
- persistent >= 2.10
- haskell-src-meta
- mtl
- template-haskell
- text

library:
  ghc-options: -Wall
  source-dirs: src

tests:
  specs:
    main:        Spec.hs
    source-dirs: test
    ghc-options: -Wall
    other-modules:
        - PersistentTestModels
        - PersistTestPetCollarType
        - PersistTestPetType
    dependencies:
        - base
        - persistent-qq
        # - aeson
        # - hspec
        # - fast-logger
        # - monad-logger
        - persistent-template
        # - persistent-sqlite
        # - resourcet
        # - text
        # - unliftio
        # - HUnit

