#!/bin/bash -e

rmdir persistent-sqlite
cabal unpack persistent-sqlite
mv persistent-sqlite-* persistent-sqlite
cabal unpack persistent-template
rmdir persistent-template
mv persistent-template-* persistent-template
cabal configure --enable-tests
cabal build
cabal test
rm -r persistent-sqlite
mkdir persistent-sqlite
rm -r persistent-template
mkdir persistent-template
