resolver: nightly-2022-12-16

packages:
  - ./persistent
  - ./persistent-sqlite
  - ./persistent-test
  - ./persistent-mongoDB
  - ./persistent-mysql
  - ./persistent-postgresql
  - ./persistent-redis
  - ./persistent-qq
