resolver: lts-14.27
packages:
  - ./persistent
  - ./persistent-sqlite
  - ./persistent-test
  - ./persistent-mongoDB
  - ./persistent-mysql
  - ./persistent-postgresql
  - ./persistent-redis
  - ./persistent-qq
