resolver: lts-2.9
packages:
  - ./persistent
  - ./persistent-template
  - ./persistent-sqlite
  - ./persistent-test
  - ./persistent-mongoDB
  - ./persistent-mysql
  - ./persistent-postgresql
  #- ./persistent-redis
  #- ./persistent-zookeeper
