resolver: lts-5.1
packages:
  - ./persistent
  - ./persistent-template
  - ./persistent-sqlite
  - ./persistent-test
  - ./persistent-mongoDB
  - ./persistent-mysql
  - ./persistent-postgresql
  - ./persistent-redis
  # - ./persistent-zookeeper

extra-deps:
  - aeson-compat-0.3.5.1
  - recursion-schemes-4.1.2
  - aeson-1.0.0.0
  - attoparsec-0.13.0.1
  - http-api-data-0.2
  - time-parsers-0.1.0.0
  - fail-4.9.0.0
  - base-compat-0.9.1
  - scientific-0.3.4.9
  - semigroups-0.18.2
  - microlens-th-0.4.1.1

flags:
  semigroups:
    bytestring-builder: false
