resolver: lts-14.27
packages:
  - ./persistent
  - ./persistent-template
  - ./persistent-sqlite
  - ./persistent-test
  - ./persistent-mongoDB
  - ./persistent-mysql
  - ./persistent-postgresql
  - ./persistent-redis
  - ./persistent-qq

extra-deps:
  - resourcet-pool-0.1.0.0
