resolver: nightly-2021-11-14

packages:
  - ./persistent
  - ./persistent-sqlite
  - ./persistent-test
  - ./persistent-mongoDB
  - ./persistent-mysql
  - ./persistent-postgresql
  - ./persistent-redis
  - ./persistent-qq

extra-deps:
  - aeson-2.0.2.0
  # https://github.com/yesodweb/shakespeare/pull/260
  - github: yesodweb/shakespeare
    commit: ea390a0e6fa25349626a0c45f133d87e3725f0ba
  # https://github.com/commercialhaskell/stackage/issues/6294
  - happy-1.20.0
