resolver: nightly-2022-01-14

packages:
  - ./persistent
  - ./persistent-sqlite
  - ./persistent-test
  - ./persistent-mongoDB
  - ./persistent-mysql
  - ./persistent-postgresql
  - ./persistent-redis
  - ./persistent-qq

extra-deps:
  - lift-type-0.1.0.0
  - mysql-0.2.1
  - mysql-simple-0.4.7
  - aeson-2.0.2.0
  # https://github.com/yesodweb/shakespeare/pull/260
  # https://github.com/commercialhaskell/stackage/issues/6294
  - happy-1.20.0