resolver: lts-3.14
packages:
  - ./persistent
  - ./persistent-template
  - ./persistent-sqlite
  - ./persistent-test
  - ./persistent-mongoDB
  #- ./persistent-mysql
  #- ./persistent-postgresql
  #- ./persistent-redis
  #- ./persistent-zookeeper

extra-deps:
  - aeson-compat-0.3.1.0
  - aeson-0.11.0.0
  - fail-4.9.0.0
  - attoparsec-0.13.0.1
  - http-api-data-0.2
