resolver: lts-14.1
packages:
  - ./persistent
  - ./persistent-template
  - ./persistent-sqlite
  - ./persistent-test
  - ./persistent-mongoDB
  - ./persistent-mysql
  - ./persistent-postgresql
  - ./persistent-redis
  - ./persistent-qq
  - ./persistent-template/compile-time-testing/projects/Mercury/

extra-deps:
  - th-lift-instances-0.1.14
