resolver: lts-11.22
packages:
  - ./persistent
  - ./persistent-template
  - ./persistent-sqlite
  - ./persistent-test
  - ./persistent-mongoDB
  - ./persistent-mysql
  - ./persistent-postgresql
  - ./persistent-redis
  - ./persistent-qq
extra-deps:
  - monad-logger-0.3.29
  - mysql-simple-0.4.5
  - postgresql-simple-0.6.1

  - mono-traversable-1.0.9.0
  - unliftio-0.2.7.0
  - unliftio-core-0.1.1.0
  - async-2.1.1.1
  - typed-process-0.2.3.0
  - resourcet-1.2.1
  - aeson-1.4.1.0
  - postgresql-libpq-0.9.4.2