resolver: lts-13.15
packages:
  - ./persistent
  - ./persistent-template
  - ./persistent-sqlite
  - ./persistent-test
  - ./persistent-mongoDB
  - ./persistent-mysql
  - ./persistent-postgresql
  - ./persistent-redis
  - ./persistent-qq

    # extra-deps:
    # - monad-logger-0.3.28.1
    # - mysql-simple-0.4.4
    # 
    # - mono-traversable-1.0.8.1
    # - unliftio-0.2.4.0
    # - unliftio-core-0.1.1.0
    # - async-2.1.1.1
    # - typed-process-0.2.1.0
    # - resourcet-1.1.11
