resolver: lts-3.4
packages:
  - ./persistent
  - ./persistent-template
  - ./persistent-sqlite
  - ./persistent-test
  - ./persistent-mongoDB
  #- ./persistent-mysql
  #- ./persistent-postgresql
  #- ./persistent-redis
  #- ./persistent-zookeeper

extra-deps:
  - aeson-extra-0.2.0.0
  - aeson-0.10.0.0
  - attoparsec-0.13.0.1
